user_name = input("What is your name?  ")
user_place = input("Give me a place... ")
user_verb1 = input("How about an infinitive verb... ")
user_food = input("What is your favorite food? ")
user_fear = input("What is your greatest fear? ")
user_years = input("Enter a number. ")
#uses string interpolation to print out the variables in the print statements.
print("\n\n\n")
print("Hi there %s, interesting seeing you in %s." % (user_name, user_place))
print("What are you doing here exactly? Well, nevermind. I've been %s in place until your return" % (user_verb1))
print("Are you hungry %s? I stole some %s for you." % (user_name, user_food))
print("In regards to our last conversation, I too am afraid of %s" % (user_fear))
print("Well, uh, great chat %s. See you again in %s years...." % (user_name, user_years))
print("\n\n\n\n")